apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statuspage-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aronheredi/devops-learn'
    targetRevision: HEAD
    path: charts/statuspage
    helm:
      valueFiles:
        - values.yaml
        - ../../envs/dev/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: statuspage-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true