apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-external-secret
  namespace: argocd # Must be placed in the argocd namespace
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: private-repo-ssh # The name of the secret ArgoCD looks for
    creationPolicy: Owner
    # CRITICAL: This block appends the labels ArgoCD requires to detect the repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd/repo-key
        property: sshPrivateKey
    - secretKey: url
      remoteRef:
        key: argocd/repo-key
        property: url
    - secretKey: type
      remoteRef:
        key: argocd/repo-key
        property: type